/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.Random;

public class Library {
    public boolean someLibraryMethod() {
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };

        Random r = new Random();
        int dicer = r.nextInt((10 - 1) + 1) + 1;//just to test, change this value
        int [] value = roll(dicer);
        boolean truthy=containsDuplicates(new int[]{3,4,5,1});
        average(weeklyMonthTemperatures);
        return true;
    }

    private boolean containsDuplicates(int[] value)
    {
        if(value.length == 0) return false;//no dups
        for(int i = 0; i < value.length; ++i){
            for(int j = i + 1; j < value.length; ++j){
                if(value[i] == value[j])
                    return true;
            }
        }
        return false;
    }

    public int[] roll(int n)
    {
        if(n == 0)
            return null;
        Random r = new Random();
        int i = 0;
        int [] array = new int [n];
        while(i < n)
        {
            array[i] = r.nextInt((6 - 1) + 1) + 1;
            ++i;
        }
        return array;
    }


    public int[] average(int[][] x)
    {
        if(x.length == 0) return null;
        int totalRow = 0,
                anAverage = 0,
                totalAverage = 0,
                lowest = (int)rowAverage(x[0])/x[0].length,
                lowestIndex = 0;
        int [] lowestAverage = new int[x.length];

        for(int i = 0 ; i < x.length; ++i)
        {
            totalRow = x[i].length;
            anAverage = rowAverage(x[i]);
            totalAverage = (int)anAverage/totalRow;
            if(lowest > totalAverage)
            {
                lowest = totalAverage;
                lowestIndex = i;
            }
        }
        return x[lowestIndex];
    }

    public int rowAverage(int [] x)
    {
        int anAverage = 0;
        for (int i = 0; i < x.length; ++i)
        {
            anAverage += x[i];
        }
        return anAverage;
    }
}
