/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.util.HashSet;

public class App {

    public static void main(String[] args)
    {
        new App().run();
    }
    public String run() {
        return "test";
    }


}
