/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.jupiter.api.Test;


class AppTest {
    @Test void testCheckSemiColonReturnsClean() {
        App sut = new App();
    }
}
